---
propertiesToRemove:
  proxy:
  - authcfg
  - proxyEnabled
  - proxyExcludeUrls
  - proxyHost
  - proxyPassword
  - proxyPort
  - proxyType
  - proxyUser
propertiesToMerge:
  svg:
  - searchPathsForSVG
  qgis:
  - customEnvVars
propertyValuesToRemove:
  svg:
    searchPathsForSVG:
    - /net0/share/qgis/svg
